changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Improvements
      labels:
        - "dependencies"
