export { detectProjectContext, type ProjectContext } from './detect-project'
export { loadPromptTemplate, type PromptVariables } from './template-prompt'
export { displayStarterPrompt } from './prompt-display'
export { runSkillInstallStep, refreshSkill, type SkillInstallResult } from './skill-install'
export { runDepsInstall, createConfig, copyChecks, type DepsInstallOptions } from './boilerplate'
export { makeOnCancel } from './prompts-helpers'
export { greeting, footer, agentFooter, existingProjectFooter, playwrightHint } from './messages'
