name: " New feature request"
description: Suggest an idea for this project
title: 'feat: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**

        This form is only for requesting a feature. If you have an usage question
        or are unsure if this functionality already exists, make sure to read our [docs](https://www.checklyhq.com/docs/) first.

        Also try to search for a similar feature - it may have already been requested or even added in the main branch.
  - type: textarea
    id: problem-description
    attributes:
      label: What problem does this feature solve?
      description: |
        Explain your use case, context, and rationale behind this feature request. More importantly, what is the **end user experience** you are trying to build that led to the need for this feature?
      placeholder: Problem description
    validations:
      required: true
  - type: textarea
    id: proposed-code
    attributes:
      label: How would you implement this feature?
      description: |
        Describe how you propose to solve the problem and provide code/api/diagram samples to use as guide. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your code blocks.
      placeholder: Steps to reproduce
    validations:
      required: true
