import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { joinPnpmLockfileDocuments, splitPnpmLockfileDocuments } from '../pnpm-lockfile-documents.js'

const FIXTURE = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  'fixtures',
  'pnpm12-lockfile',
  'pnpm-lock.yaml',
)

const ENV = `lockfileVersion: '9.0'

importers:

  .:
    packageManagerDependencies:
      pnpm:
        specifier: 12.3.4
        version: 12.3.4
`

const MAIN = `lockfileVersion: '9.0'

importers:

  .:
    devDependencies:
      '@playwright/test':
        specifier: ^1.58.2
        version: 1.63.0
`

describe('splitPnpmLockfileDocuments', () => {
  it('treats a file without a leading marker as a single application document', () => {
    expect(splitPnpmLockfileDocuments(MAIN)).toEqual({ main: MAIN })
  })

  it('separates the environment document from the application document', () => {
    expect(splitPnpmLockfileDocuments(`---\n${ENV}\n---\n${MAIN}`)).toEqual({ env: ENV, main: MAIN })
  })

  it('yields an empty application document for an environment-only file', () => {
    expect(splitPnpmLockfileDocuments(`---\n${ENV}`)).toEqual({ main: '' })
  })

  it('normalizes CRLF line endings before looking for the markers', () => {
    const crlf = `---\n${ENV}\n---\n${MAIN}`.replace(/\n/g, '\r\n')
    expect(splitPnpmLockfileDocuments(crlf)).toEqual({ env: ENV, main: MAIN })
  })

  it('ignores a leading byte order mark', () => {
    expect(splitPnpmLockfileDocuments(`\uFEFF---\n${ENV}\n---\n${MAIN}`)).toEqual({ env: ENV, main: MAIN })
    expect(splitPnpmLockfileDocuments(`\uFEFF${MAIN}`)).toEqual({ main: MAIN })
  })

  it('does not mistake a marker inside the application document for a separator', () => {
    const withInnerMarker = `${MAIN}\n---\nunrelated: true\n`
    expect(splitPnpmLockfileDocuments(withInnerMarker)).toEqual({ main: withInnerMarker })
  })

  it('reads the application document of a lockfile generated by pnpm 12', async () => {
    const content = await fs.readFile(FIXTURE, 'utf8')
    const { env, main } = splitPnpmLockfileDocuments(content)

    expect(env).toContain('packageManagerDependencies:')
    expect(env).not.toContain('@playwright/test')
    expect(main.startsWith('lockfileVersion: \'9.0\'')).toBe(true)
    expect(main).toContain('\'@playwright/test@1.63.0\':')
    expect(main).not.toContain('packageManagerDependencies:')
  })
})

describe('joinPnpmLockfileDocuments', () => {
  it('returns the application document alone when there is no environment document', () => {
    expect(joinPnpmLockfileDocuments({ main: MAIN })).toBe(MAIN)
  })

  it('reattaches the environment document with its markers', () => {
    expect(joinPnpmLockfileDocuments({ env: ENV, main: MAIN })).toBe(`---\n${ENV}\n---\n${MAIN}`)
  })

  it('yields nothing for an environment-only file, as pnpm itself would', () => {
    // pnpm keeps no environment document without an application document
    // behind it, and the writers in this codebase never reach the join for
    // such a file: with an empty application document there is nothing to
    // rewrite.
    expect(joinPnpmLockfileDocuments(splitPnpmLockfileDocuments(`---\n${ENV}`))).toBe('')
  })

  it('round-trips a lockfile generated by pnpm 12 byte for byte', async () => {
    const content = await fs.readFile(FIXTURE, 'utf8')
    expect(joinPnpmLockfileDocuments(splitPnpmLockfileDocuments(content))).toBe(content)
  })
})
