module.exports = {
  'us-east-1': {
    region: 'us-east-1',
    name: 'N. Virginia',
    flag: '/static/images/icons/vendor/flags/us.svg',
    color: '#1f77b4',
  },
  'us-east-2': {
    region: 'us-east-2',
    name: 'Ohio',
    flag: '/static/images/icons/vendor/flags/us.svg',
    color: '#aec7e8',
  },
  'us-west-1': {
    region: 'us-west-1',
    name: 'N. California',
    flag: '/static/images/icons/vendor/flags/us.svg',
    color: '#ff7f0e',
  },
  'us-west-2': {
    region: 'us-west-2',
    name: 'Oregon',
    flag: '/static/images/icons/vendor/flags/us.svg',
    color: '#ffbb78',
  },
  'ca-central-1': {
    region: 'ca-central-1',
    name: 'Montreal',
    flag: '/static/images/icons/vendor/flags/canada.svg',
    color: '#2ca02c',
  },
  'sa-east-1': {
    region: 'sa-east-1',
    name: 'São Paulo',
    flag: '/static/images/icons/vendor/flags/brazil.svg',
    color: '#98df8a',
  },
  'eu-west-1': {
    region: 'eu-west-1',
    name: 'Ireland',
    flag: '/static/images/icons/vendor/flags/ireland.svg',
    color: '#d652b1',
  },
  'eu-central-1': {
    region: 'eu-central-1',
    name: 'Frankfurt',
    flag: '/static/images/icons/vendor/flags/germany.svg',
    color: '#ff9896',
  },
  'eu-west-2': {
    region: 'eu-west-2',
    name: 'London',
    flag: '/static/images/icons/vendor/flags/uk.svg',
    color: '#9467bd',
  },
  'eu-west-3': {
    region: 'eu-west-3',
    name: 'Paris',
    flag: '/static/images/icons/vendor/flags/france.svg',
    color: '#c5b0d5',
  },
  'eu-north-1': {
    region: 'eu-north-1',
    name: 'Stockholm',
    flag: '/static/images/icons/vendor/flags/sweden.svg',
    color: '#8c564b',
  },
  'eu-south-1': {
    region: 'eu-south-1',
    name: 'Milan',
    flag: '/static/images/icons/vendor/flags/italy.svg',
    color: '#1fd535',
  },
  'me-south-1': {
    region: 'me-south-1',
    name: 'Bahrain',
    flag: '/static/images/icons/vendor/flags/bahrain.svg',
    color: 'rgba(99,16,50,0.85)',
  },
  'ap-southeast-1': {
    region: 'ap-southeast-1',
    name: 'Singapore',
    flag: '/static/images/icons/vendor/flags/singapore.svg',
    color: '#c49c94',
  },
  'ap-northeast-1': {
    region: 'ap-northeast-1',
    name: 'Tokyo',
    flag: '/static/images/icons/vendor/flags/japan.svg',
    color: '#e377c2',
  },
  'ap-east-1': {
    region: 'ap-east-1',
    name: 'Hong Kong',
    flag: '/static/images/icons/vendor/flags/china.svg',
    color: '#e3b85d',
  },
  'ap-southeast-2': {
    region: 'ap-southeast-2',
    name: 'Sydney',
    flag: '/static/images/icons/vendor/flags/australia.svg',
    color: '#f7b6d2',
  },
  'ap-northeast-2': {
    region: 'ap-northeast-2',
    name: 'Seoul',
    flag: '/static/images/icons/vendor/flags/south-korea.svg',
    color: '#7f7f7f',
  },
  'ap-northeast-3': {
    region: 'ap-northeast-3',
    name: 'Osaka',
    flag: '/static/images/icons/vendor/flags/japan.svg',
    color: '#e377c2',
  },
  'ap-south-1': {
    region: 'ap-south-1',
    name: 'Mumbai',
    flag: '/static/images/icons/vendor/flags/india.svg',
    color: '#c7c7c7',
  },
  'af-south-1': {
    region: 'af-south-1',
    name: 'Cape Town',
    flag: '/static/images/icons/vendor/flags/south-africa.svg',
    color: '#deca22',
  },
}
