name: Publish create-checkly to npmjs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter create-checkly publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Slack failure alert
      - name: Slack Failure Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_USERNAME: Checkly Github Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: cli
          SLACK_ICON: https://github.com/checkly.png?size=48
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: ':red_circle: NPM release of create-cli failed'
          SLACK_MESSAGE: by ${{ github.actor }}
          SLACK_FOOTER: ''
      # Slack success alert
      - name: Slack Success Notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_USERNAME: Checkly Github Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: cli
          SLACK_ICON: https://github.com/checkly.png?size=48
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: ':white_check_mark: NPM release of create-cli succeeded'
          SLACK_MESSAGE: by ${{ github.actor }}
          SLACK_FOOTER: ''
